### ISSUE TITLE
crazy(?) idea: apps that are just templates & queries

### ISSUE THREAD

**Issue by dominictarr** [ssbc/ssb-server#127]
Okay so spent a few days hacking on [mynosql](https://github.com/dominictarr/mynosql)
and then I hooked it up to secure-scuttlebutt to get some real data, and did a few queries.

Everything was pretty fast, even though it was using optimized queries for everything.
That is because there is only small data so far. However, I don't think this is a problem,
because we can easily add indexes later, and mynosql already supports compound indexes,
just after a few days hacking.

Then I had a strange idea... if we have a flexible, generic query langage, so that we can retrive arbitary data... maybe we can just render that data via templates... and if the templates can also be used to create NEW data... then we might have enough to create at least basic apps just using templates.
That would really take us back to mid 90s style decentralized web... And of course, templates are much easier to audit than code...

**Comment by No9** [comment]
Don't take this the wrong way but that sounds a lot like Cocoon :)
http://cocoon.apache.org/2.0/userdocs/concepts/ 
(Tigger warning: XML, UML Long Object namespaces) 

Conceptually it was a great idea but suffered from the "Ant" problem where you basically end up programming in XML configuration files. 

Would be interested in seeing another pass at that approach tho

**Comment by ralphtheninja** [comment]
@dominictarr What is compound indexes?

**Comment by pfraze** [comment]
@dominictarr I agree with this and I've been thinking about it again for Phoenix - we need to render unknown message types and create filters/views of the timeline, and I think

**Comment by pfraze** [comment]
sorry, last comment was prematurely submitted. retrying -

@No9 has a good point. It needs to simple and effective to be worthwhile

phoenix could use something like this to render message types. I'd like these to be shared on the network and be safe to run. ie a dev would post a renderer when they introduce a new message type, and their followers would have it as a "Render as..." option once those raw messages start showing up. more like "shared config" than shared software

we've talked about markdown templates before, and about extending markdown to allow gui elements. that's something to consider.

**Comment by dominictarr** [comment]
@no9 haha now "logicsheet" is in my vocabulary!

@ralphtheninja see mynosql documentation or post an issue there if it didn't clarify.

@No9 hmm, I remember being scared of ant. There is certainly a danger of recreating the silliest XML stuff but with JSON, and then our children do it again with YAML. But there is also the danger that there is actually some good ideas there and that if we don't try we'll loose them. I'm having a bit of trouble seeing how cocoon actually works... Is there a better example or can you explain?

**Comment by ahdinosaur** [comment]
@dominictarr hmm, i think this is a direction worth exploring, seems like a continuation of materialized data views which feels good.

> phoenix could use something like this to render message types. I'd like these to be shared on the network and be safe to run. ie a dev would post a renderer when they introduce a new message type, and their followers would have it as a "Render as..." option once those raw messages start showing up. more like "shared config" than shared software

@pfraze  yes, this! :watermelon:

**Comment by No9** [comment]
@dominictarr

I think this is the most important diagram for understanding cocoon
![Cocoon](http://cocoon.apache.org/2.0/userdocs/concepts/images/interaction-sequence.gif)

Cocoon has a "SiteMap" which is an XML file that contains a list of endpoints that cocoon listens to and these endpoints are mapped to pipelines.

Think of it like a configurable connect router https://www.npmjs.com/package/connect-route
Where the routes are mapped to modules declaratively in a config rather than imperatively as shown in the sample on the connect-route page.

When Cocoon gets a request to an endpoint that it knows about it invokes a "pipeline" 

![pipeline](http://cocoon.apache.org/2.0/userdocs/concepts/images/pipeline.gif)

The sample in this image is a basic one but it really says: 

1. Take a source data provider (In this case a File Generator) 

2. Apply a transform to it (an XSLT in cocoon world) 

3. Pass the output of the transform to a HTML serializer that could do anything from just setting the mime/type in the response to applying addition general styling/content. 

The beauty of this approach was every thing was just XML so you could merge multiple pipelines and not have to worry about formats

This may be a challenge for us as most of the time we would want to pipeline JSON and output it too a HTML template/serializer but there may be moments when we want to pipeline HTML to a HTML templates. i.e. Possibly In a site menu scenario

The real nightmare came when you needed to include new functionality into the XSLT parser if the functionality wasn't currently built in. This meant building XSLT extensions and had a lot of friction. 
Also the tools for debugging these custom XSLT transformations were very convoluted.  

A way around that was the "logicsheet" that you mentioned but as you can see from this sample 
http://cocoon.apache.org/2.1/userdocs/xsp/logicsheet.html 

It was programming in XML :-1:

**Comment by dominictarr** [comment]
Aha, I sense I need to research XLST. SHIT! wikipedia says xlst is turning complete...
Though, it's so verbose that the simplest examples on the wikipedia page are more verbose than implementing the same in a procedural language with a XML parser library...

checkout example 2 https://en.wikipedia.org/wiki/XSLT#Example_2_.28transforming_XML_to_XHTML.29
The "XLST template" is longer than the input and output put together!!!

I feel like that doesn't disprove that "data templates" are a bad idea, just because XLST is a committee design.
