### ISSUE TITLE
boradcast-stream and udp6

### ISSUE THREAD

**Issue by darkdrgn2k** [ssbc/ssb-server#513]
I'm trying to create gossip connections over UDP ipv6
I know that UDP ipv6 does not support "broadcasts"  however this can still be useful in unicast

For example with CJDNS we know our directly peered partners and can emit a unicast packet to those peers to see if there is a possibility there.

Alternatively gossip.connect can be used by 3rd party programs to establish more intelligent connections

I tried copying the the ipv4 code to ipv6 in broadcast stream however have run into a bit of a roadblock

https://cryptpad.fr/code/#/2/code/view/wPqr91GK4bLJ+6VULN0qrUunkC7uxY-LbFQiZx+HdpI/

Is there a better way of doing this? or a better place in the code to make the adjustment for udp ipv6 port 8008 functionality?

**Comment by Happy0** [comment]
I don't know the details of UDP ipv6 broadcasting, but perhaps it'd make more sense to make broadcast-stream/index.js configurable to use ipv6 with a flag?

At the moment the module returns a socket. So that module could return either an ipv6 socket or an ipv4 socket, depending on the configuration parameters that are passed in.

For example, `module.exports = function (port, loopback) ` could become `module.exports = function (port, loopback, useIpv6) {` 

If the 'useIpv6' flag is 'true', then the socket that's returned by the module would be configured appropriately for ipv6.

https://github.com/ssbc/scuttlebot/blob/master/plugins/local.js could then construct both an ipv4 and ipv6 (if appropriate to the device and network) instance of 'broadcast-stream'.

Someone else came into the scuttlebutt IRC channel and expressed interest in UDP ipv6 broadcast for the following usecase:

```
 ideally, the multicast announcements would be performed via IPv6 link-local multicast. or would be configurable. as I'd be interested in combining it with batman-adv (a layer 2 mesh routing protocol which currently only has some optimizations for IPv6 link-local multicast)                                                                                                             
```

I read this article on the differences between ipv4 vs ipv6 udp broadcast: https://serverfault.com/questions/227442/why-cant-ipv6-send-broadcasts . I'm struggling to understand the low level network stuff, but I'll try to read about it in more depth later.

**Comment by jedahan** [comment]
So I've been experimenting with a [udp6 multicast broadcast-stream](https://github.com/dominictarr/broadcast-stream/compare/master...jedahan:master), there are a lot of moving parts to make it seamless though.

* create udp6 broadcast-stream constructor
* modify local.js to use udp6 constructor
* modify secret-stack to use ipv6
* make sure multiserver/plugins/net supports ipv6
  * add 'opts.host' to plugins/net::server.listen() (weird because opts is passed into net.createServer...)
* make sure secret-stack/index.js can instantiate multiserver/plugins/net as ipv6
  * make sure secret-stack/getAddress returns the correct ipv6 address

The four main places that need to be worked on that I've identified so far are broadcast-stream, secret-stack, multiserver/plugins/net, and scuttlebot.

Regarding learning multicast, I recommend installing socat. It has support for sending udp6 multicast packets, but not listening exactly.

So I wrote this quick-and-dirty proof of concept for listening to udp6 multicast in node

https://github.com/jedahan/autodiscover/blob/master/server.js

**Comment by jedahan** [comment]
I'd definitely be open to doing a video/voicechat to discuss how we could all work together easily, or we can continue conversation here and/or on scuttlebutt.

**Comment by Happy0** [comment]
That's fantastic that you're already working on it =].

Ah, it was actually the correct 'broadcast address' to use that confused me the most because I'd read that ipv6 only lets you broadcast to certain groups of devices in the resource I found - but looking at your code (which uses the dns-sd address) made that make more sense.

It looks like you've basically already done bullet point 1? I may have time to help with other parts in about a month if you or others haven't done it already. I'll probably need to get my hands dirty in those same areas next month anyway (to do another task).

**Comment by jedahan** [comment]
@Happy0 well fingers crossed I'll be working on this more full-time and will attempt to stream development on twitch & use collaborative code editors so you can pop in whenever is convenient

**Comment by T-X** [comment]
Hi @jedahan, IPv6 multicast listener issues were fixed in socat v1.7.3.2 not that long ago. After that the following command worked for me:

``$ socat -u UDP6-RECV:1234,reuseaddr,ipv6-join-group="[ff12::123]:eth0" -``

(Before that fix I had also written my own, small C code to create a listener :D. https://github.com/T-X/sm-listener)

@darkdrgn2k, @Happy0: In IPv6 there is always the "ff02::1" all-hosts multicast address. Which essentially is a broadcast. And for instance switches will always treat it very much like that, e.g. switches will always (have to) flood that to all of their ports as this is the only address which is excempted from the whole, prior multicast listener discovery part (MLD).

But please don't think about using ff02::1. The "always broadcast ff02::1" rule prohibits network/routing protocol developers from doing optimizations.

**Comment by jedahan** [comment]
@T-X oh awesome! I guess I was reading some outdated info, this will definitely help with debugging. Though I am having trouble finding 'en0' 
```
socat -u udp6-recv:1234,reuseaddr,ipv6-join-group="[ff02::114]:en0" -
2018/07/03 12:50:36 socat[58350] E interface "en0" not found
```
tried with lo0, en1, gonna have to look at the source to figure out why macOS is not giving the right interface...

I wonder what the most minimal local udp broadcast chat client is, without having to install socat. Like maybe using netcat or a usb to bootstrap something, anyway I digress...

I've been using `ff02::114` for now, which is designated 'experimental', we should definitely pick something better once we are ready to upstream.

**Comment by darkdrgn2k** [comment]
Not related to the UDP6 component but we had issues with the UDP4 broadcasts.  So we wrote our on script to send out UDP packets. Script and observations can be found here.
(see here https://github.com/benhylau/ssbc-grants-scuttlemesh/issues/5#issuecomment-391556068 )

Our hope was to use the same mechanism to send out uni cast packets over ipv6 (which seemed allot easier then broadcast, but only because we know our neighbors)

**Comment by jedahan** [comment]
My fork of broadcast-stream now does broadcast over udp6 `ff02::114`, and I was able to get scuttlebot to broadcast the ipv6 address with `ssb_host=$(ifconfig en0 | grep ipv6 | cut -d' ' -f2 | cut -d'%' -f1) npm start`

It is hacky but this is what wireshark shows:

<img width="1000" alt="screen shot 2018-07-15 at 11 36 10 am" src="https://user-images.githubusercontent.com/32407/42741447-5321d5d6-8880-11e8-86af-ec12df64ef61.png">

Gossiping may not happen yet - gotta see if sbot is listening on `::1` or theres more work to be done.
Also that ipv6 address is hacky, but im having a lot of trouble figure out all the places config.host can be set, and where is appropriate.

a node hack to get link-local ipv6 addresses...

```js
const os = require('os')
const interfaces = os.networkInterfaces()
const isLinkLocalAddress = ({address}) => address.startsWith('fe80')
const isEthernet = interface => interface.startsWith('e') // hack for ethX / enpXsY

const localAddresses = Object.entries(interfaces)
  .filter(([interface, _]) => isEthernet(interface))
  .map(([_, addresses]) => addresses.find(isLinkLocalAddress))
  .map(({address}) => address)

console.dir(localAddresses)
```
