### ISSUE TITLE
Issue in sending transactions

### ISSUE THREAD

**Issue by devashish-laitkor** [ssbc/ssb-server#515]
Hi,

Getting this error.

Error1:-

at Socket.<anonymous> (/home/ubuntu/blockfin/validator/node_modules/stream-to-pull-stream/index.js:158:5)
     at emitNone (events.js:111:20)
     at Socket.emit (events.js:208:7)
 server error, from net:::ffff:52.44.3.10:60316~shs:
 Error: expected challenge
     at abort (/home/ubuntu/blockfin/validator/node_modules/secret-handshake/protocol.js:80:45)
     at Object.cb (/home/ubuntu/blockfin/validator/node_modules/secret-handshake/protocol.js:84:24)
     at drain (/home/ubuntu/blockfin/validator/node_modules/pull-reader/index.js:42:23)
     at /home/ubuntu/blockfin/validator/node_modules/pull-reader/index.js:59:18
     at /home/ubuntu/blockfin/validator/node_modules/pull-reader/index.js:20:7
     at /home/ubuntu/blockfin/validator/node_modules/pull-stream/throughs/through.js:19:9
     at drain (/home/ubuntu/blockfin/validator/node_modules/stream-to-pull-stream/index.js:141:18)
     at Socket.<anonymous> (/home/ubuntu/blockfin/validator/node_modules/stream-to-pull-stream/index.js:158:5)
     at emitNone (events.js:111:20)
     at Socket.emit (events.js:208:7)

Error2:-

OpenError: IO error: lock .ssb/node/flume/clock/LOCK: Resource temporarily unavailable
    at /home/ubuntu/blockfin/messagenode/node_modules/level-packager/node_modules/levelup/lib/levelup.js:117:34
    at /home/ubuntu/blockfin/messagenode/node_modules/leveldown/node_modules/abstract-leveldown/abstract-leveldown.js:39:16
You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
OpenError: IO error: lock .ssb/node/db/LOCK: Resource temporarily unavailable
    at /home/ubuntu/blockfin/messagenode/node_modules/level/node_modules/levelup/lib/levelup.js:91:23
    at /home/ubuntu/blockfin/messagenode/node_modules/level/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /home/ubuntu/blockfin/messagenode/node_modules/level/node_modules/deferred-leveldown/deferred-leveldown.js:20:21
    at /home/ubuntu/blockfin/messagenode/node_modules/encoding-down/node_modules/abstract-leveldown/abstract-leveldown.js:41:14
    at /home/ubuntu/blockfin/messagenode/node_modules/level/node_modules/abstract-leveldown/abstract-leveldown.js:41:14

**Comment by cryptix** [comment]
Sorry but how are these two errors related? It's hard to give any feedback without usage code to reproduce.

`OpenError: IO error: lock .ssb/node/flume/clock/LOCK: Resource temporarily unavailable` sounds like you opened the same `$HOME/.ssb` twice.

`Error: expected challenge` sounds like an overloaded `sbot server` which is unable to accept connections.

**Comment by devashish-laitkor** [comment]
Hi @cryptix 

Thanks for your response.. Is there any limitations of `sbot server` for accepting connection or its system resources issue???

**Comment by cryptix** [comment]
You can only start one `sbot server` per `$HOME/.ssb` folder. The IO Lock errors seem to imply that you are trying to start multiple ones, or that you are not using the right client-code to run your query or publish operations.

Re accepting connections: same as above. Since nodejs is single-threaded it can get into a _busy state_ where connection attempts time out. Then you see the `expected challenge` error. Faster machines can reduce this but you can also use the config to reduce sheduling of outgoing connections or disable automatic outgoing gossiping outright and use `sbot gossip.connect` to trigger them manually.

**Comment by devashish-laitkor** [comment]
Hi @cryptix ,

Thanks for your response.
My architecture is something like this https://www.screencast.com/t/hpaYtwRRmFXV, I have currently deployed it on AWS , for each instance, configuration is 8 CPU, 16 GB RAM

**Comment by cryptix** [comment]
All of this is on one instance? then your _prcessing nodes_ would be using ssb-client.

The storage nodes would either have to configure individual _repo folders_ (.ssb/) or run them as individual Unix users with their own `$HOME`s.

I’m not sure why you want so many storage nodes on a single box. Please consider the _offline first_ design and equivalence of peers/nodes. all of them will share all the data, there is no sharding.

You could attempt some kind of _social sharding_ by pasrtitioning the friend graph but then the processing nodes can’t connect to all the storage nodes. Personally I don’t see much sense in that apart from sharing load but then you definitely tune down their gossiping because that will have massive overhead.

**Comment by devashish-laitkor** [comment]
All nodes are running on individual virtual machines.
