### ISSUE TITLE
sbot publish --dry-run

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#574]
The more time I spend hacking around with `sbot` the more I wish I could append some `--dry-run` flag to get the results of a command without actually running it. Ideally I'd like a valid post that *could* be appended to my feed but isn't, but any solution would be useful. I think the easiest solution would be to just publish under a disposable identity, but I'm unsure whether that's even possible.

Anyone know how difficult this would be, or which roadblocks we might face?

**Comment by dominictarr** [comment]
great idea! this would be easy. just return from here https://github.com/ssbc/secure-scuttlebutt/blob/master/minimal.js#L202 without passing the message to queue. that will give you a valid message.

It might be better to create an _invalid_ message, though. so that you won't fork your feed if you add it later. If a random `opts.hmacKey` is set: https://github.com/ssbc/secure-scuttlebutt/blob/master/minimal.js#L193 then that message will look completely valid (you could pass it to any renderer) but the signature won't validate. I recommend setting a random hmac key when using --dry-run by default, maybe with an option to disable that if you really think it's a good idea.
