### ISSUE TITLE
Separate `bin.js` into its own ssb-cli module

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#602]
I've seen this mentioned before but wasn't sure how everyone felt about it. Personally, I'd be happy to maintain `bin.js` in its own module which *depends* on ssb-server, but I'd like to know how everyone else feels about this.

Backlink: https://github.com/ssbc/ssb-server/issues/378#issue-216043396

**Comment by dominictarr** [comment]
what do we gain from this? you still can't use one without the other.
there is less code in ssb-server... but it's gonna have another module that is tightly coupled to it. doesn't seem like a change that really makes much difference to me?

**Comment by dominictarr** [comment]
oh right, but if you renamed the command to `ssb-server` then it doesn't make any sense that you are using it for all the commands. so I guess it _has_ to be another command.

**Comment by christianbundy** [comment]
One benefit is that you'd be able to install ssb-server without also installing all of the non-mandatory plugins we're including in `bin.js`.

I don't feel very strongly about separating this out, but it seems like we're tightly coupling the recommended plugins with the bare ssb-server dependency tree. This means that it's impossible to run ssb-server without also having to install dependencies for `bin.js`, even for applications that never touch the CLI.

**Comment by dominictarr** [comment]
separating default dependencies is a good idea, but doesn't ssb-server need to keep those... so to get that we'd need a raw ssb-server-core plus ssb-server-opinions and then ssb-cli

**Comment by dominictarr** [comment]
if ssb-server doesn't have the defaults, then how do we ship the defaults?
maybe ssb-server should just wrap scuttlebot (which is now not user facing) and scuttlebot has minimal deps, and ssb-server has all the opinions in it.

**Comment by dominictarr** [comment]
note though, ssb-server only has a single command.

**Comment by dominictarr** [comment]
more thoughts here: what _is_ the-module-formally-known-as-scuttlebot, _really?_

The main thing in index.js is actually a secret-stack plugin. it's 180 lines, but it's just glue around `ssb-db`. just enough to be able to do `SecretStack.use(ssbDb)`, basically. It doesn't add any interesting features. now there is a server, but actually `secret-stack` provides that. All the real actually in the ssb-server repo is in plugins folder, or it's the plugins that are required. If we published gossip and legacy replication, and the other things in the plugins folder, and required them again, then `ssb-server` would just become a bunch of opinions. A curation of plugins.

The other important thing is the tests folder. If those modules were refactored out, then the tests would be too, obviously. but I think a really valuable thing about ssb-server _is_ the tests. or at least, confirming that everything still runs with the combination of deps that have been loaded. If it was possible to install all the plugins into the curation module, then run all those plugin's tests (and in those tests, run deps loaded in the ssb-server shrinkwrap).

**Comment by ahdinosaur** [comment]
> note though, ssb-server only has a single command.

@dominictarr yes, that's what i'm proposing. are you saying this is good or bad?

**Comment by ahdinosaur** [comment]
> If we published gossip and legacy replication, and the other things in the plugins folder, and required them again, then `ssb-server` would just become a bunch of opinions. A curation of plugins.

i'm pretty keen on this!

there's also another thread where the module-formally-known-as-scuttlebot is given a proper burial and is composted into many ssb servers. of these, i'm most interested in what @mmckegg is calling lessbot (`%1bz0TXDuaM65KMTb8bgtrXuqD7L77baneTdoJ0EwRug=.sha256`), which is the minimum server necessary to achieve replication and writing to the log. 

because i think it's important to notice that most consumers of the module-formally-known-as-scuttlebot, like Patchwork and Patchbay, are not actually using the module directly, they are using the plugins to construct their own curated server. even for PeachCloud, i'm planning to follow the lead of Patchwork and be more opinionated about how the server is put together. then if lessbot is successful, we won't need to agree on a common set of plugins to use, or even a common plugin interface, only the most minimal server that replicates and writes to the `log.offset`.

**Comment by dominictarr** [comment]
@ahdinosaur no objections to having a single command. although if it's own one command, don't need to do `ssb-server start` just do `ssb-server`. That's a very minor point though.

If we are gonna have a prolifferation of sbot (sorry, that slipped out) distributions (which I support) I just wanna do it in such a way that we can be at least as confidant as now that they _still work_. so, if there is an easy way to create a distribution, bundle some plugins together, _but run all their tests, on the bundle_ before you hit publish, then I'll be very pleased. If we are trying to make it easier to contribute then I think this is important because if contributors are afraid of breaking things they'll be afraid to contribute.

**Comment by dominictarr** [comment]
one thing here, is that currently, these tests are doing `require('scuttlebot')`
that needs to be replaced with a distribution name... most straightforward way is to pass that in as an enviroment variable.

**Comment by dominictarr** [comment]
i mean `require(SSB_SERVER || 'ssb-server')`... hmm.
or, we instead we do `require('secret-stack).use(require('ssb-db'))` (which is the same as doing `require('ssb-server')` now, and then the way require works (looking into parent directories `../node_modules ../../node_module, ...` it will find all the correct modules)

**Comment by staltz** [comment]
I really support refactoring out replication and gossip and other plugins into their own repositories, so that this "sbot" can be simply a curation of opinions, but a curation described in less than 50 lines of code (currently it's not, because of built-in plugins). Then it would be easier to create new curations.

Also agree that the tests are highly valuable.

**Comment by reqshark** [comment]
> the way require works (looking into parent directories ../node_modules ../../node_module, ... it will find all the correct modules)

ya that's correct. much love for require.

especially after doing import. after the whole ecmas**t standard track around `import` statement... sorry not trying to derail but what a brutal regression from `require`!

> Also agree that the tests are highly valuable.

Testing opinions is the only way I can fully understand why they're right.

Like one of those Rich Hickey videos where he talks about "Guardrail Programming." Just because a bunch of arbitrary use-cases confirm everything we're supposed to think: do you still wanna go driving down the road banging back and forth off the guardrails to know where the edge was? No when you're diving down the road, you would try to keep an eye forward, come on. In fact, when you're not paying attention to guard rails or constraints, that's exactly where good code is written. Reason about your program flow without acknowledging that, because too much testing either feedbacks into complexity or merely re-proves that callbacks actually work. :) testing that a param or function returns the way it was intended is just falling into the whole meaningless coverage trap, go conspire against simplicity! Yet on the flip side when something is hard to test it may be due to excessive complexity in the code, or even just like thinking about guardrails instead of looking forward onward and upward

great test codes don't reveal some special limitation on what's possible, nah I think good tests are more just cool documentation about where you were going

**Comment by dominictarr** [comment]
btw, I ended up just creating a test dep script that created a symlink in `node_modules/ssb-server -> ../`
https://github.com/ssbc/ssb-server/blob/master/test/deps.sh#L5
