### ISSUE TITLE
How should we specify devDependencies for integration tests?

### ISSUE THREAD

**Issue by christianbundy** [ssbc/ssb-server#625]
I don't think this is the global optima, but as a local optima for cross-module integration tests I'd be open to using your idea as a postinstall script that gathers plugin devDependencies and adds them to our lockfile. This has three benefits:

1. Increased determinism for our testing.
2. It's automatic and always remains up-to-date.
3. Contributors don't have to learn anything new.

cc: @dominictarr (I've closed #623 because you pushed your commits straight to `master` instead)

**Comment by dominictarr** [comment]
hmm, I was just trying to revert https://github.com/ssbc/ssb-server/commit/95785cb598043c1b820f3ef6cf708a579585de36 I thought it was just a tiny thing but then I realized it wasn't, so I reverted that and am making it a PR now.

**Comment by dominictarr** [comment]
see also: https://github.com/ssbc/ssb-server/pull/626

**Comment by dominictarr** [comment]
creating a tool to do this was in the back of my mind when I was creating the https://github.com/ssbc/ssb-server/blob/master/test/deps.sh script.

how should it work? I'm thinking a tool you install as a dev dep
* `deptest add <module>` # adds to {} in package.json that this is an extra tested dep, installs and adds it's dev deps.
* `deptest test` run tests for all tested deps.
* `deptest test <module>` run just the tests for a particular module (using `cd node_module/<module>&& npm test`)
* `deptest ls` check that all deps are correct.

note, before running the tests, deptest would add a symlink as in #626 and then would remove it after.
the only problem is we can't gaurantee that deptest fully completes, so sometimes `npm ls` might break. thus i recommend having a `deptest ls`

this would be useful for distributions of parts that have tests that are interdependent on each other (such as ssb or browserify) or for modules that have dependents that you do not want to break.

**Comment by christianbundy** [comment]
How would this hypothetical module handle conflicting devDependencies?

For example, if ssb-gossip depends on cont@1.0.0 and ssb-replicate depends on cont@2.0.0, which do we add to the devDependencies of ssb-server?

> I do not agree that lockfiles to each of those projects is the right solution. The point is to test those modules with ssb-server's deps, not with the deps specified when ssb-gossip or what have you's deps. (the plugins deps are probably old, I don't want to go and publish new versions of all the plugins just because one has been updated)

I didn't originally respond to this, but I want to point out that this isn't the case for the strategy I used in #623. The steps are basically:

1. `installed=$(npm ls)` with some plumbing to get the module names
2. for each plugin:
    1. `pushd node_modules/ssb-plugin-name` for each plugin
    2. `npm install --only=dev` (or `npm ci` to respect lockfile)
    3. `rm -rf $installed` to ensure we aren't shadowing any parent dependencies
    4. `npm test`
    5. `popd` to start again for the next plugin

I wouldn't mind this being extracted into its own tooling, but I think this may be one of the only ways we can do deep integration tests for child dependencies without having to specify the [potentially conflicting] dependencies in the parent module.

**Comment by dominictarr** [comment]
yes, this is a good point - but I think in practice this is a small problem.
there will be a few test frameworks and stuff, but they are probably fairly easy to keep up to date.
you could have a thing that does installs, and then merges the deep deps into the shrinkwrap as needed, but that will be fairly complicated. I suggest just leaving this as a TODO until it actually becomes a problem.

**Comment by christianbundy** [comment]
I have to admit I'm not super excited about adding the constraint that "all devDependencies for plugin modules must remain compatible", and I'm having trouble understanding why we should do it that way. Could you help me understand a bit more about why you aren't comfortable with my proposal?

I appreciate that you're responding to each of my proposals (#617 + #623), but it feels like your responses have been mostly counter-proposals (#618 + #626) rather than comments about the code I've written. Right now it sounds to me like we have two options:

1. **Dynamic:** automatically test each plugin by installing necessary devDependencies, symlinking ssb-server, and running `npm test`. Deep devDependencies aren't added to the parent lockfile.
2. **Static:** manually hardcode the necessary devDependencies of each plugin to `package.json`, cross your fingers that they're all compatible, and require that other developers learn and stick to this system. Deep devDependencies are added to the parent lockfile.

It's clear that we're weighing the pros and cons differently, so I'm looking for your input on why the dynamic plugin devdeps are unacceptable or how you'd imagine they might cause problems.

**Comment by dominictarr** [comment]
My main thing is I want it to be statically locked down. I don't want to do npm install on every test run because it will be offline-unfriendly. That is bigger for me than the risk of a conflict between two plugin's test utils.

I don't mind if you use npm install to generate the combined lock file, but I want to know for sure it's static when you actually run the tests.
I do acknowledge that testing dev deps could conflict and this would be a problem - I just don't expect there to be many extra devdeps, so I think it's unlikely to be a big problem in practice. This only affects the test framework and test utils used. For ssb's tests, everything uses tape, which is extremely stable. I don't know about other test frameworks but that isn't our problem.

I'm not against handling this edgecase - I just think it's not worth the effort yet. If _I_ was implementing this, I'd just skip that for now. If you are gonna implement something for it then go ahead, I just think you'll spend more time working on it than you'll save. Up to you. I'd rather not waste lots of time writing testing tools, which is why I just started with a bash script and managing extra dev deps manually.

Maybe you could put the extra deps into the lockfile (in the right place to avoid conflicts) then ask npm to install that... I'm not sure if npm would cooperate there. If it did you could have very good, static, integration tests, that avoided conflicts.

**Comment by dominictarr** [comment]
I'd also like to emphasize that there are very few extra dev deps:

```
    "cat-names": "^2.0.0",
    "dog-names": "~1.0.2",
    "interleavings": "^0.3.1",
    "pull-bitflipper": "^0.1.0",
    "run-series": "^1.1.8",
    "ssb-generate": "^1.0.1",
    "tape": "^4.9.1"
```
cat-names dog-names are used by ssb-replicate and ssb-ebt, interleavings and pull-bitflipper is used by ssb-blobs, run-series is used by ssb-friends. ssb-generate is used by ssb-friends and ssb-ebt.
everything uses tape. There are only 7 deps. If there where 20, maybe I'd be worried about conflicts.
