### ISSUE TITLE
Local broadcast broken

### ISSUE THREAD

**Issue by cryptix** [ssbc/ssb-server#640]
I think local UDP advertisments are currently borken:

<img width="836" alt="screenshot 2019-02-22 at 17 45 27" src="https://user-images.githubusercontent.com/111202/53221580-eda9c580-36ce-11e9-824e-daf3bf6806f8.png">

**Comment by cryptix** [comment]
May I ask why the IP was in this payload to begin with? Shouldn’t it be the src ip of the broadcast that’s gets connected to? Much easier to get right, also for v6.

**Comment by cryptix** [comment]
@christianbundy told me he already reported this. Is it fixed though?

**Comment by staltz** [comment]
I also got another report about this issue https://gitlab.com/staltz/manyverse/issues/333#note_143889112

**Comment by christianbundy** [comment]
This was opened as https://github.com/ssbc/patchwork/issues/943 and I pushed a PR to resolve this in Patchwork as https://github.com/ssbc/patchwork/pull/944, but I think this is also resolved by https://github.com/ssbc/multiserver/pull/40.

I think this is an issue with Patchwork and Patchbay rather than ssb-server. Related: should we be merging all of the default "if we're on Unix, use a unix socket" code into ssb-config? It feels strange to use the same shared boilerplate across all of the clients.

**Comment by dominictarr** [comment]
That is definitely wrong. It should not be advertising a device address - that's `noauth`! it should be using a local address. that shouldn't be using a device address since this commit: https://github.com/ssbc/ssb-server/commit/1556f6317a9ca1899a6e0617b3728013bcdda465 (that should be in ssb-server@14)

May depend on @ahdinosaur's config though, but `noauth` should only be used in a device scope, not a `local/private` scope

**Comment by cryptix** [comment]
I fear this goes deeper:

<img width="1105" alt="screenshot 2019-02-24 at 14 03 10" src="https://user-images.githubusercontent.com/111202/53293673-03d59400-383d-11e9-8784-60e4c8a403f7.png">

This is a broadcast from my recent patchbay. I'm not sure the v6 link local is dialable? It might.. The websock surely also isn't.

**Comment by staltz** [comment]
Would be useful to know how does the ssb config object look like for each of these broadcasting devices.

**Comment by dominictarr** [comment]
@cryptix test if this works: `sbot getAddress local` should give a 192.168... address

aha, patchbay is misconfigured: https://github.com/ssbc/patchbay/blob/master/config.js#L36
unix socket should be `device` scope, not `local`

the [documentation](https://github.com/ssbc/ssb-config#connections) says:
 

*    private - bind only to local network i.e. wifi/lan
*    public - bind to public ip address (it's likely you do not have a public address on an end device, but some networks do)
*    local - _alias to private_
*    device - "localhost". accessable only on the same device.

**Comment by christianbundy** [comment]
Yeah, both Patchwork and Patchbay are misconfigured, so I think the majority of [Unix] users are broadcasting their socket address over UDP. I've got a PR open into Patchwork but the original bug reporter says it's causing "Error {}" to be printed repeatedly. No idea.
