### ISSUE TITLE
Pub being deleted from the wiki

### ISSUE THREAD

**Issue by klarkc** [ssbc/ssb-server#690]
Liberty Network Pub (Ancap group) is being removed from the wiki by members of ssbc org. It's against any rules? I could not find any rule, please let me know if I am wrong.

https://github.com/ssbc/ssb-server/wiki/Pub-Servers/_history

**Comment by christianbundy** [comment]
Hey @klarkc.

I can't speak for anyone else, but *personally* I'd be uncomfortable with right-wing/capitalist politics in the wiki. There aren't any rules about this, but support removing ancap pubs from the wiki. If other SSBC folks feel differently I'd be open to discussion, but otherwise I'd imagine that the pub should not be re-added to the wiki.

cc: @Powersource @keks (just wanted you to be aware of this discussion, no action required)

**Comment by Powersource** [comment]
Pretty much what Christian said.

**Comment by klarkc** [comment]
Ok, thanks for the reply.
