### ISSUE TITLE
Clear pub messages

### ISSUE THREAD

**Issue by mrweiss** [ssbc/ssb-server#693]
Hi,

I'm hosting a pub (full access to the server/files) and would like to clear all messages to 'start over' - would deleting a 'database' file be enough? I'd ideally want to retain the 'new user hello' messages, but not too important if not possible..

(can't tag it as a type:question)

Thank you!

**Comment by christianbundy** [comment]
Hi! I'd be happy to help.

Are you comfortable creating a new identity, or do you want to keep the identity you currently have on the server? If you're okay with getting a new identity you can delete `~/.ssb/` and restart the server, which will *truly* start over, but it won't download any new messages or anything because it's a completely new feed.

**Comment by mrweiss** [comment]
thanks! was hoping it will be as simple as that (was just wondering which file/folder to delete) .. fine with the new identity/identities for everyone involved
